--liquibase formatted sql

--changeset formationreact:1 dbms:h2
create table if not exists application(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nom varchar(100),
    version varchar(100),
    etat varchar(100)
);
--rollback drop table application;